export const REQUEST_BEERS_PAGE = 'REQUEST_BEERS_PAGE';
export const RECEIVE_BEERS_PAGE = 'RECEIVE_BEERS_PAGE';

export const REQUEST_BEER_DETAILS = 'REQUEST_BEER_DETAILS';
export const RECEIVE_BEER_DETAILS = 'RECEIVE_BEER_DETAILS';